export const TRANSLATIONS: Record<string, Record<string, string>> = {
  English: {
    // Navigation & Header
    settings: 'Settings',
    welcomeBack: 'Welcome back',
    radar: 'Radar',
    inspiration: 'Inspiration',
    creation: 'Creation',
    marketplace: 'Marketplace',
    community: 'Community',
    investors: 'Investors',
    chat: 'Chat',
    saved: 'Saved',
    profile: 'Profile',
    newProject: 'New Project',
    searchEverything: 'Search everything...',
    switchAccount: 'Switch Account',
    language: 'Language',

    // Settings
    globalLanguage: 'Global Language',
    feedLayout: 'Feed Layout',
    aiInterventionLevel: 'AI Intervention Level',
    backupConfiguration: 'Backup Configuration',
    terminateAllSessions: 'Terminate All Sessions',
    advancedDefinitions: 'Advanced Definitions',
    customizeExperience: 'Customize your Unihia experience to match your workflow and style.',
    visualInterface: 'Visual Interface',
    themeMode: 'Theme Mode',
    accentColor: 'Accent Color',
    typography: 'Typography',
    systemAi: 'System & AI',
    aiInterventionDesc: 'Higher levels allow AI to suggest more proactive collaborations and strategic shifts.',

    // Radar Feed
    aiOpportunities: 'AI-Orchestrated Opportunities',
    livePulse: 'Live Pulse • Real-time',
    matchScore: 'Match Score',
    opportunities: 'Opportunities',
    connect: 'Connect',
    accept: 'Accept',
    match: 'Match',

    // Inspiration Feed
    executeIdea: 'Execute Idea',
    translateTo: 'Translate to',
    saveToLibrary: 'Save to Library',
    executeProject: 'Execute Project',
    transformToProject: 'Transform to Project',
    save: 'Save',

    // Creation Lab
    ideaLaboratory: 'Idea Laboratory',
    transformSpark: 'Transform your spark into a structured execution plan with Orchestrated AI.',
    describeVision: 'Describe your vision... (e.g., A marketplace for carbon credits using blockchain)',
    generateRoadmap: 'Generate Strategic Roadmap',
    phase: 'Phase',

    // Marketplace
    innovationMarket: 'Innovation Market',
    acquireInvest: 'Acquire, license, or invest in verified high-potential assets.',
    filter: 'Filter',
    sort: 'Sort',
    roi: 'ROI',
    viewDetails: 'View Details',
    startup: 'Startup',
    prototype: 'Prototype',
    businessModel: 'Business Model',

    // Community
    activeRooms: 'Active Project Rooms',
    joinRoom: 'Join Room',
    suggestedCollaborators: 'AI-Suggested Collaborators',
    leaderboard: 'Reputation Leaderboard',
    globalImpact: 'Global Impact',
    target: 'Target',
    members: 'members',
    tasksPending: 'tasks pending',
    globalImpactDesc: 'Unihia has facilitated over $2.4M in project funding this month.',
    expertIn: 'Expert in Blockchain & Rust',

    // Investors
    availableLiquidity: 'Available Liquidity',
    activeFunds: 'Active Funds',
    avgRoi: 'Avg. ROI',
    opportunitiesForYou: 'Investment Opportunities for You',
    investNow: 'Invest Now',
    contactFounder: 'Contact Founder',
    highPotential: 'HIGH POTENTIAL',
    valuation: 'Valuation',
    raised: 'Raised',
    impact: 'Impact',
    global: 'Global',
    mockInvestmentDesc: 'Seeking $500k for Series A. 15% Equity.',

    // Chat
    searchChats: 'Search chats...',
    aiOrchestratorActive: 'AI Orchestrator Active',
    aiSuggestion: 'AI ORCHESTRATOR SUGGESTION',
    applySuggestion: 'Apply Suggestion',
    typeMessage: 'Type your message...',
    today: 'Today',
    mockAiChat: 'AI: I suggest we focus on the MVP first...',
    mockUserChat: "Hey team, how's the roadmap looking for the smart city project?",
    mockUserResponse: 'The AI just finished the Phase 1 analysis. It looks solid!',
    mockAiSuggestion: "Based on current progress, I recommend integrating the 'Neural Interface' pin from Alex's inspiration feed to enhance Phase 2.",

    // Saved Library
    personalLibrary: 'Personal Library',
    curatedCollection: 'Your curated collection of inspiration and execution.',
    libraryEmpty: 'Your library is empty',
    savePrompt: 'Save pins, ideas, or projects from the feed to see them here.',
    category: 'Category',
    all: 'All',
    pin: 'Pin',
    idea: 'Idea',
    project: 'Project',

    // Profile
    verifiedArchitect: 'Verified Architect',
    topExecution: 'Top 1% Execution',
    editProfile: 'Edit Profile',
    share: 'Share',
    reputation: 'Reputation',
    projects: 'Projects',
    investments: 'Investments',
    collaborations: 'Collaborations',
    executionHistory: 'Execution History',
    successfullyExited: 'Successfully exited for',

    // AI Triad / System
    aiThinking: 'AI is orchestrating your request...',
    aiResponseError: 'The AI Orchestrator encountered a synchronization error. Please retry.',
    geminiActive: 'Gemini 3.1 Pro Active',
    claudeActive: 'Claude 3.5 Sonnet Active',
    gptActive: 'GPT-4o Active'
  },
  Portuguese: {
    // Navigation & Header
    settings: 'Configurações',
    welcomeBack: 'Bem-vindo de volta',
    radar: 'Radar',
    inspiration: 'Inspiração',
    creation: 'Criação',
    marketplace: 'Mercado',
    community: 'Comunidade',
    investors: 'Investidores',
    chat: 'Chat',
    saved: 'Salvos',
    profile: 'Perfil',
    newProject: 'Novo Projeto',
    searchEverything: 'Pesquisar tudo...',
    switchAccount: 'Trocar Conta',
    language: 'Idioma',

    // Settings
    globalLanguage: 'Idioma Global',
    feedLayout: 'Layout do Feed',
    aiInterventionLevel: 'Nível de Intervenção de IA',
    backupConfiguration: 'Backup da Configuração',
    terminateAllSessions: 'Encerrar Todas as Sessões',
    advancedDefinitions: 'Definições Avançadas',
    customizeExperience: 'Personalize sua experiência Unihia para combinar com seu fluxo de trabalho e estilo.',
    visualInterface: 'Interface Visual',
    themeMode: 'Modo de Tema',
    accentColor: 'Cor de Destaque',
    typography: 'Tipografia',
    systemAi: 'Sistema e IA',
    aiInterventionDesc: 'Níveis mais altos permitem que a IA sugira colaborações mais proativas e mudanças estratégicas.',

    // Radar Feed
    aiOpportunities: 'Oportunidades Orquestradas por IA',
    livePulse: 'Pulso ao Vivo • Tempo Real',
    matchScore: 'Pontuação de Match',
    opportunities: 'Oportunidades',
    connect: 'Conectar',
    accept: 'Aceitar',
    match: 'Match',

    // Inspiration Feed
    executeIdea: 'Executar Ideia',
    translateTo: 'Traduzir para',
    saveToLibrary: 'Salvar na Biblioteca',
    executeProject: 'Executar Projeto',
    transformToProject: 'Transformar em Projeto',
    save: 'Salvar',

    // Creation Lab
    ideaLaboratory: 'Laboratório de Ideias',
    transformSpark: 'Transforme sua centelha em um plano de execução estruturado com IA Orquestrada.',
    describeVision: 'Descreva sua visão... (ex: Um marketplace para créditos de carbono usando blockchain)',
    generateRoadmap: 'Gerar Roadmap Estratégico',
    phase: 'Fase',

    // Marketplace
    innovationMarket: 'Mercado de Inovação',
    acquireInvest: 'Adquira, licencialize ou invista em ativos verificados de alto potencial.',
    filter: 'Filtrar',
    sort: 'Ordenar',
    roi: 'ROI',
    viewDetails: 'Ver Detalhes',
    startup: 'Startup',
    prototype: 'Protótipo',
    businessModel: 'Modelo de Negócio',

    // Community
    activeRooms: 'Salas de Projetos Ativas',
    joinRoom: 'Entrar na Sala',
    suggestedCollaborators: 'Colaboradores Sugeridos por IA',
    leaderboard: 'Ranking de Reputação',
    globalImpact: 'Impacto Global',
    target: 'Meta',
    members: 'membros',
    tasksPending: 'tarefas pendentes',
    globalImpactDesc: 'Unihia facilitou mais de $2.4M em financiamento de projetos este mês.',
    expertIn: 'Especialista em Blockchain & Rust',

    // Investors
    availableLiquidity: 'Liquidez Disponível',
    activeFunds: 'Fundos Ativos',
    avgRoi: 'ROI Médio',
    opportunitiesForYou: 'Oportunidades de Investimento para Você',
    investNow: 'Investir Agora',
    contactFounder: 'Contatar Fundador',
    highPotential: 'ALTO POTENCIAL',
    valuation: 'Valuation',
    raised: 'Captado',
    impact: 'Impacto',
    global: 'Global',
    mockInvestmentDesc: 'Buscando $500k para Série A. 15% de Participação.',

    // Chat
    searchChats: 'Pesquisar conversas...',
    aiOrchestratorActive: 'Orquestrador de IA Ativo',
    aiSuggestion: 'SUGESTÃO DO ORQUESTRADOR DE IA',
    applySuggestion: 'Aplicar Sugestão',
    typeMessage: 'Digite sua mensagem...',
    today: 'Hoje',
    mockAiChat: 'IA: Sugiro focarmos no MVP primeiro...',
    mockUserChat: 'Ei equipe, como está o roadmap para o projeto da cidade inteligente?',
    mockUserResponse: 'A IA acabou de terminar a análise da Fase 1. Parece sólido!',
    mockAiSuggestion: "Com base no progresso atual, recomendo integrar o pin 'Neural Interface' do feed de inspiração do Alex para aprimorar a Fase 2.",

    // Saved Library
    personalLibrary: 'Biblioteca Pessoal',
    curatedCollection: 'Sua coleção curada de inspiração e execução.',
    libraryEmpty: 'Sua biblioteca está vazia',
    savePrompt: 'Salve pins, ideias ou projetos do feed para vê-los aqui.',
    category: 'Categoria',
    all: 'Tudo',
    pin: 'Pin',
    idea: 'Ideia',
    project: 'Projeto',

    // Profile
    verifiedArchitect: 'Arquiteto Verificado',
    topExecution: 'Top 1% em Execução',
    editProfile: 'Editar Perfil',
    share: 'Compartilhar',
    reputation: 'Reputação',
    projects: 'Projetos',
    investments: 'Investimentos',
    collaborations: 'Colaborações',
    executionHistory: 'Histórico de Execução',
    successfullyExited: 'Saída bem-sucedida por',

    // AI Triad / System
    aiThinking: 'IA está orquestrando sua solicitação...',
    aiResponseError: 'O Orquestrador de IA encontrou um erro de sincronização. Por favor, tente novamente.',
    geminiActive: 'Gemini 3.1 Pro Ativo',
    claudeActive: 'Claude 3.5 Sonnet Ativo',
    gptActive: 'GPT-4o Ativo'
  }
};
